export const QUERY_KEYS = {
  securities: ['securities2'] as const,
  security: (id: number) => ['security', id] as const,
  securityEquityModelPortfolios: (id: number) =>
    ['security-equity-model-portfolios', id] as const,
  portfolio: (name: string) => ['portfolio', name] as const,
  portfolios: ['portfolios'] as const,
  positions: (portfolioName: string) => ['positions', portfolioName] as const,
  atRisk: ['at_risk'] as const,
  atRiskBySecurity: (securityId: string) => ['at_risk', securityId] as const,
  prospects: ['prospects'] as const,
  prospectsBySecurity: (securityId: string) => ['prospects', securityId] as const,
  reviewSchedules: ['review_schedules'] as const,
  reviewSchedule: (securityId: string) => ['review_schedules', securityId] as const,
  reviewLog: (securityId: string) => ['review_log', securityId] as const,
  actionItems: ['action_items'] as const,
  actionItemsBySecurity: (securityId: string) => ['action_items', 'security', securityId] as const,
  actionItemsByPortfolio: (portfolioName: string) => ['action_items', 'portfolio', portfolioName] as const,
  rebalanceLog: (portfolioName: string) => ['rebalance_log', portfolioName] as const,
  portfolioPerformance: (portfolioName: string, start: string, end: string) =>
    ['portfolio_performance', portfolioName, start, end] as const,
  portfolioPeriodReturns: (portfolioName: string) => ['portfolio_period_returns', portfolioName] as const,
  portfolioMovers: (portfolioName: string, days: number) => ['portfolio_movers', portfolioName, days] as const,
  allocationGrid: (portfolioName: string) => ['allocation_grid', portfolioName] as const,
  latestActualAllocation: (portfolioName: string) => ['latest_actual_allocation', portfolioName] as const,
  sp500SectorWeights: ['sp500_sector_weights'] as const,
  alertRules: (securityId: string) => ['alert_rules', securityId] as const,
  alertEvents: ['alert_events'] as const,
  clients: ['clients'] as const,
  client: (id: number) => ['client', id] as const,
  clientPortfolios: (clientId: number) => ['client_portfolios', clientId] as const,
  communicationLog: (clientId: number) => ['communication_log', clientId] as const,
  substitutions: (atRiskId: number) => ['substitutions', atRiskId] as const,
  allComplianceRules: ['compliance_rules_all'] as const,
  complianceRules: (portfolioName: string) => ['compliance_rules', portfolioName] as const,
  holdingsChangeLog: (portfolioName: string) => ['holdings_change_log', portfolioName] as const,
  auditLog: (tableName?: string, page?: number) => ['audit_log', tableName ?? 'all', page ?? 0] as const,
  actionItemEvents: (actionItemId: number) => ['action_item_events', actionItemId] as const,
  portfoliosHoldingSecurity: (securityId: string) => ['portfolios_holding_security', securityId] as const,
  benchmarks: ['benchmarks', 'v4'] as const,
  sectorBenchmarks: ['sector_benchmarks', 'v2'] as const,
  relatedSecurities: (securityId: string) => ['related_securities', securityId] as const,
  fundComparison: (securityId: string) => ['fund_comparison', securityId] as const,
  ips: (clientId: number) => ['ips', clientId] as const,
  ipsModelCompatibility: (clientId: number) => ['ips_model_compatibility', clientId] as const,
  tradeSuitability: (portfolioName: string) => ['trade_suitability', portfolioName] as const,
  householdMembers: (householdName: string) => ['household_members', householdName] as const,
  householdPositions: (householdName: string) => ['household_positions', householdName] as const,
  portfolioReviews: (portfolioName: string) => ['portfolio_reviews', portfolioName] as const,
  portfolioReviewSchedules: ['portfolio_review_schedules'] as const,
  portfolioReviewSchedulesFor: (portfolioName: string) => ['portfolio_review_schedules', portfolioName] as const,
  holdingReviews: (portfolioName: string) => ['holding_reviews', portfolioName] as const,
  securityAdditions: (portfolioName: string) => ['security_additions', portfolioName] as const,
  securityAddition: (id: number) => ['security_addition', id] as const,
  researchReports: (securityId: string) => ['research_reports', securityId] as const,
  researchReportsForAddition: (additionId: number) => ['research_reports', 'addition', additionId] as const,
  riskReports: (portfolioName: string) => ['risk_reports', portfolioName] as const,
  riskReportsForAddition: (additionId: number) => ['risk_reports', 'addition', additionId] as const,
  icMemos: (portfolioName: string) => ['ic_memos', portfolioName] as const,
  icMemo: (id: number) => ['ic_memo', id] as const,
  icMemosForAddition: (additionId: number) => ['ic_memos', 'addition', additionId] as const,
  documentsFiles: (bucket: string) => ['documents-files', bucket] as const,
  modelPortfolios: ['model_portfolios'] as const,
  modelPortfolioByObjective: (objective: string) => ['model_portfolio_by_objective', objective] as const,
  modelPortfolioById: (id: number) => ['model_portfolio_by_id', id] as const,
  directModelPortfolioId: (securityId: string) => ['direct_model_portfolio_id', securityId] as const,
  benchmarkByName: (name: string) => ['benchmark_by_name', name] as const,
  benchmarkAllByName: (name: string) => ['benchmark_all_by_name', name] as const,
  categoryBenchmark: (category: string) => ['cat-benchmark', category] as const,
  peerGroupBenchmark: (name: string) => ['pg-benchmark', name] as const,
  categoryBenchmarksTable: ['category-benchmarks'] as const,
  peerGroupBenchmarksTable: ['peer-group-benchmarks'] as const,
  sectorBenchmarksTable: ['sector-benchmarks'] as const,
  modelPortfolioBenchmarksTable: ['model-portfolio-benchmarks'] as const,
  modelPortfolioBenchmarkOptions: ['model-portfolio-benchmark-options'] as const,
  securitySearch: (prefix: string) => ['security-search', prefix] as const,
  transcript: (securityId: string) => ['transcript', 'latest', securityId] as const,
  firmComplianceRules: ['firm_compliance_rules'] as const,
  allPortfolioPositions: ['all_portfolio_positions'] as const,
  clientPortfolioNames: ['client_portfolio_names'] as const,
  financialsData: (symbol: string) => ['financials_data', 'v8', symbol] as const,
  financialsAnnualData: (symbol: string) => ['financials_annual_data', 'v1', symbol] as const,
  revenueSegments: (symbol: string, kind: string, period: string) =>
    ['revenue_segments', 'v1', symbol, kind, period] as const,
  analystData: (symbol: string) => ['analyst_data', 'v4', symbol] as const,
  keyExecutives: (symbol: string) => ['key_executives', symbol] as const,
  ratiosTTM: (symbol: string) => ['ratios_ttm', symbol] as const,
  ratiosAnnual: (symbol: string) => ['ratios_annual', 'v2', symbol] as const,
  fcfMargins: (symbol: string) => ['fcf_margins', 'v2', symbol] as const,
  cagr3y: (symbol: string) => ['cagr_3y', 'annual', symbol] as const,
  ttmGrowth: (symbol: string) => ['ttm_growth', symbol] as const,
  profile: (symbol: string) => ['profile', symbol] as const,
  quote: (symbol: string) => ['quote', symbol] as const,
  earningsDates: (symbol: string) => ['earnings_dates', symbol] as const,
  stockReturns: (symbol: string) => ['stock_returns', symbol] as const,
  scorecardMetrics: (symbol: string) => ['scorecard_metrics', symbol] as const,
  stockNews: (symbol: string) => ['stock_news', symbol] as const,
  pressReleases: (symbol: string) => ['press_releases', symbol] as const,
  indexConstituents: (index: string) => ['index_constituents', index] as const,
  indexBaselines: (index: string) => ['index_baselines', index] as const,
}
